import Header from "@/components/Header";
import Navbar from "@/components/Navbar";
import { poppins } from "@/styles/fonts";
import clsx from "clsx";
import type { Metadata } from "next";
import "../globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
      <html lang="en">
        <body className={clsx([poppins.className])}>
          <Header />
          <Navbar />
          {children}
        </body>
      </html>
  );
}
